countdown = input("how many seconds are left before launch?\n->")
oxygen_tanks = input("how many oxygen tanks are onboard?\n->")
food_packs = input("how many food packs are on board?\n->")
water_packs = input("how many water packs are onboard?\n->")

print("countdown: "+ countdown)
print("oxygen_tanks:"+ oxygen_tanks)
print("food_packs:"+ food_packs)
print("water_packs:"+water_packs)
oxygen_tanks = input("Confirm oxygen tank supply\n->")

print("Countdown: "+ countdown)
print("Oxygen Tanks: "+ oxygen_tanks)
print("Food Packs: "+ food_packs)
print("water Packs: "+water_packs)
