time = input("countdown ")
oxygen = input("oxygen_tanks")
food = input("food_packs")
water = input("water_packs")
print("countdown: "+ time)
print("oxygen_tanks"+ oxygen)
print("food_packs"+ food)
print("water_packs"+water)
oxygen = input("confirm oxygen tanks")
print("countdown: "+ time)
print("oxygen_tanks"+ oxygen)
print("food_packs"+ food)
print("water_packs"+water)